### ISSUE TITLE
Improve title look up when not in frontmatter

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#186]
Domain: "https://launchpad-nqv5jpw2a32p.curve.space/"
Source: "https://github.com/ageron/handson-ml2.git"

This launchpad test seemed to go particularly wrong

**Comment by fwkoch** [comment]
This is a case of bad title discovery - all the notebooks have a `# Setup` in the ~3rd cell, when the actual title is just bold in the first cell.

We should change the logic to only look at the first cell (if no frontmatter), and maybe find bold text there? (though this could be funny if someone has like `Warning: this notebook is in **prerelease**` above everything else... hah) Then fall back to file name before looking deeper in the notebook cells.
