### ISSUE TITLE
Logo is not copied correctly on deploy

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenote#219]
We rewrite logo to a specific place in the public folder, but the site does not map it correctly on upload.

Here I had logo/rowan.png

Site works fine, deploy:
![image](https://user-images.githubusercontent.com/913249/175210508-8f581ee7-61a7-4f15-95a2-618dbf431b6f.png)

**Comment by stevejpurves** [comment]
note: the fully resolved paths stem from recent windows fixes

**Comment by rowanc1** [comment]
This has been fixed!
