### ISSUE TITLE
images on github don't work in curvenote init or launchpad

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#235]
Looks like this is an increasingly common case, see: https://github.com/cegaldev/cegaltools

The images in the README and the notebook point to github, but point to the HTML page for the asset rather than the raw asset, as this renders fine on github, it looks like launchpad is broken - so I think we should address this by remapping the links to their raw counterparts.

Current launchpad for this repo: https://launchpad-z45hxl3ae94d.curve.space/cegaltools

**Comment by rowanc1** [comment]
Works!

![image](https://user-images.githubusercontent.com/913249/180317500-b3d27cac-5c05-4b88-849c-8ed085ceec62.png)
