### ISSUE TITLE
Allow links to downloadable files to be added to a curve.space site

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#250]
* when working locally - this issue https://github.com/curvenote/curvenotejs/issues/176 will address this
* When working in curvenote - the files should be placed in the `public` folder of the deployment, and a relative link should be added to the content in curvenote's editor e.g. `public/myfile.pdf` - this won;t be testable in curvenote - this will require changes to link validation to work i.e. https://github.com/curvenote/editor/issues/136

**Comment by rowanc1** [comment]
This now works!
