### ISSUE TITLE
Bold text not rendering as expected?

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#266]
Example:

![image](https://user-images.githubusercontent.com/1473646/163815699-a9242fd2-6e2e-48e2-acfc-fb5cd5187ec7.png)

in: https://climasoma.curve.space/report/eu-policy-instruments-driving-soil-management

**Comment by rowanc1** [comment]
I think this is now obsolete, the commonmark that we wrote was not correct.
