### ISSUE TITLE
Enable automatic export to pdf using templates that require pdflatex

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#307]
Some LaTeX templates contain `pdflatex` specific macros and must be built using that build command. For example, EGU Copernicus https://github.com/curvenote/templates1/issues/4 requires this.

PR #306 adds the correct build command to run pdflatex

In order to make this possible on a per template basis and enable builds from curvenote.com, we need to:

 - [ ] Extend the `template.yml` schema, currently defined in the `jtex` package to include a field such as `build` or `engine` which can be `xelatex` or `pdflatex`
 - [ ] in the Curvenote CLI we already fetch the template spec (`template.yml`) in order to determine the tagged blocks required by the template. We should refactor and move that call so that the `engine` option can be used appropriately in the build pdf function call

**Comment by rowanc1** [comment]
This is now complete! EGU builds well!
