### ISSUE TITLE
Export overhaul

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#315]
Objectives:
 - Export local content to DOCX, PDF
 - move `jtex` to TS, use as a library in cli
 - Change export from API to use local export methods & simplify
 - update templates, Curvenote cloud export fn support latest frontmatter / authors changes

Things:
 - [x] Local DOCX export
 - [x] Lift validation/frontmatter to separate packages
 - [x] Pull template management from cli to jtex
 - [x] Validation of template yml and options to populate it
 - [x] Add `export` and template options to frontmatter and pass through to jtex
   - `template`, `output`
   - `export` -> `exports`, `tagged` -> `parts`
   - `doc` - move `frontmatter` type opts to here
   - `str/bool` -> `string/boolean`
 - [x] Add `packages` to template yml 
 - [x] Update all templates to be compatible with new jtex
 - [x] Fix templates for author, affiliation etc.
 - [x] Fix image paths into tex zip folder (rather than temp folder)
   - If copying image to same folder it is already in, don't hash...
 - [x] Project (authors) frontmatter, needs to flow though to exports
 - [x] Local LaTeX Export from mdast
 - [x] make myst-to-latex complete (like-for-like with schemas toTex behaviour)
 - [x] Update CLI  Export from API to use local export methods
 - [x] Update curvenote cloud functions to use new cli
    - [x] get private templates working (docx)
 - [x] Fix up app 
   - [x] #367
   - [x] #370
   - [x] #368
   - [x] #369
 - [x] #371
 - [x] #372
 - [x] Local PDF Export
 - [x] https://github.com/curvenote/curvenote/issues/307
 - [x]  #340

**Comment by rowanc1** [comment]
Lots of this merged in #322

**Comment by stevejpurves** [comment]
@rowanc1 check out the issues linked above for a flavor of what @fwkoch and I went over - please add comments / edit as needed

**Comment by rowanc1** [comment]
All deployed and migrated today!
