### ISSUE TITLE
Support Book Exports

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenote#374]
An example here:

* https://goodresearch.dev/index.html

Right now we don't have too many solid latex templates, and not a good way of exporting entire sites as books (including TOCs, frontmatter, etc.).

**Comment by rowanc1** [comment]
Some code here:
https://github.com/patrickmineault/codebook/blob/main/assemble_onepager.py

**Comment by echarles** [comment]
So for now a pdf can only be generated from a single markdown, right?

The linked code just above could be used as source of inspiration. Another source of inspiration (in terms of features on latex leve) could be the R [bookdown](https://github.com/rstudio/bookdown) package which I have used previously and is very user-friendly ([doc](https://bookdown.org/yihui/bookdown/)).

What about as very first draft implementation concatenating all markdown defined in the yaml, and only after convert to latex and pdf?

**Comment by rowanc1** [comment]
Thanks for the comments @echarles, I will transfer this issue over to EBP and continue the conversation over there. It is really interesting to see how folks were already hacking around the CLI to get the latex converted. I will take another look for inspiration on UI/CLI design from bookdown! Thanks for the comment. :)

**Comment by echarles** [comment]
> Thanks for the comments @echarles, I will transfer this issue over to EBP and continue the conversation over there.

@rowanc1 Is the issue transferred?  I am curious to know how the plan have evolved to support the generation of a single PDF that contain multiple markdown/notebook pages.

**Comment by rowanc1** [comment]
I have "transferred" the issue over to EBP to continue the discussion:

- https://github.com/executablebooks/mystjs/issues/203

I don't think that our thinking has evolved too much, I would like to give this a try sometime in the next few weeks. I think there might be maybe a custom _toc for the project, or exports in the project, or -- just a new article that has imports (similar to how you would do this in latex). I think all are valid, but might need a bit of experimentation.

@stevejpurves just did this for a 230 page book, and might have some insights!! Lets talk over in EBP!
