### ISSUE TITLE
LaTeX section headers one level below

### ISSUE THREAD

**Issue by stggh** [curvenote/curvenote#467]
I am not sure whether this issue belongs here, please advise.

Recently, the  section headers generated for a PDF/LaTeX document are one level below. i.e `# Header` yields `\subsection{Header}`.

e.g. test.md:
```
---
title:  Test
authors:
  - name: Stephen Gibson
    email: Stephen.Gibson@anu.edu.au
exports:
  - format: pdf
    template: curvenote
    output: exports/test.pdf
keywords:
date:
---

# Section
This is section.

## subsection
A subsection. 

## subsubsection
A subsubsection.

# Section 2
Section 2.


# Section 3
Section 3.

## Subsection 3
Subsection 3
```

`myst build test.md --pdf` produces: 
![image](https://github.com/curvenote/curvenote/assets/10932229/090ff592-f95b-405b-8a39-26dafa3d1688)

The corresponding tex file is:
```tex
% Created with jtex v.1.0.13
\documentclass{article}
\PassOptionsToPackage{short, nodayofweek}{datetime}

\input{curvenote.def}



% colors for hyperlinks
\hypersetup{colorlinks=true, allcolors=blue}
\hypersetup{
pdftitle={\@title},
pdfsubject={},
pdfauthor={\@author},
pdfkeywords={},
addtopdfcreator={Written in Curvenote}
}

\usepackage{curvenote}

\title{Test}

\newdate{articleDate}{1}{2}{2024}
\date{\displaydate{articleDate}}

\author{\bfseries Stephen Gibson\mdseries\\}

\begin{document}

\maketitle
\keywords{}

\subsection{Section}

This is section.

\subsubsection{subsection}

A subsection.

\subsubsection{subsubsection}

A subsubsection.

\subsection{Section 2}

Section 2.

\subsection{Section 3}

Section 3.

\subsubsection{Subsection 3}

Subsection 3
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%  acronyms & glossary  %%%%%%%%%%%%%
\printglossaries
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
```

With headings one level lower than they should be.

**Comment by stevejpurves** [comment]
Thanks for opening the issue @stggh!

It looks like you are using the `mystmd` CLI rather than the `curvenote` CLI?

The curvenote CLI leans on mystmd for this conversion, and there have been some changes there, which are not yet released in the `curvenote` cli.

If you are using myst, it's best to open an issue on that repo directly (https://github.com/executablebooks/mystmd/issues), note that this change (https://github.com/executablebooks/mystmd/pull/860) is maybe what has affected you?
cc @fwkoch

**Comment by stggh** [comment]
@stevejpurves thanks for your eloquent and detailed answer. I will follow the links that you have provided.

**Comment by fwkoch** [comment]
@stggh - I put together a fix for this here: https://github.com/executablebooks/mystmd/pull/885 - should go out in the next MyST release!
