### ISSUE TITLE
Ensure that optional checks are shown as optional in online check UI

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#532]
These checks are exposed in the build page for a job (you can get this from the cli output on submission or from the admin UI)

We need to ensure that we have `optional: true` set for some checks in the local dev db (scipy is currently the best local development site)

After that we should be able to fix up the build page to ensure that optional checks are shown appropriately.

Dupe: https://github.com/curvenote/journals/issues/244

Related/Extra-Credit: https://github.com/curvenote/journals/issues/251

**Comment by rowanc1** [comment]
This was also necessary in the cli: #540
