### ISSUE TITLE
Latest version is dependent on list sorting

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenote#544]
There is a bug fixed in #543, that looks to the top of the list rather than the bottom because the sort-order of the versions in the API changed. This bug fix needs to be done independent of the sort order of that array, probably by posting to `submission/{id}/versions` and getting the `submissionVersion` back, and then asking for more information about the submission if we need it (I don't think we do?).

**Comment by stevejpurves** [comment]
>  we need a better pattern there that isn’t relying on the sorting of that list

> Ah, yeah, it’s a bit strange that the API for new submission version is POST /v1/sites/<site>/submissions/<id> and returns the full submission. Probably ought to be POST /v1/sites/<site>/submissions/<id>/versions and just returns the version…
Then we can just have normal sorting on the GET .../versions endpoint, rather than ambiguous sorting on the .versions field of the .../submissions/<id> endpoint…

**Comment by fwkoch** [comment]
New versions endpoint here: https://github.com/curvenote/curvenote/pull/554
